### PR TITLE
Update Pyroclasm.txt

### PR DESCRIPTION
**Pull request by PalladiaMors**
Suggesting cast with AI hint.

### CODE REVIEW

**Comment by melvinzhang** [comment]
@ShawnieBoy in the future, please rebase the patch on top of master instead of merge, we prefer to keep the history linear

**Comment by ShawnieBoy** [comment]
No probs, was just experimenting with using the website to merge

**Comment by melvinzhang** [comment]
See method 2 in http://blog.differential.com/best-way-to-merge-a-github-pull-request/ that's the one we are using. github doesn't support it natively.

**Comment by PalladiaMors** [comment]
By the way, do we all agree that this is a safe Cast with AI hint? I can think of a few reasons to remove your own creatures - maybe you need to get rid of something enchanted with Pillory of the Sleepless, or you could want to damage your own Boros Reckoner. It's very rare to find one of these things without any drawbacks, but overall I think this one should lead to a net improvement - plays worse on some rare situations, but better on most situations.

**Comment by melvinzhang** [comment]
I'm fine with this, I see it as an extension of the negative target hint we currently use for targeted damage dealing.

**Pull request merged**
