### PR TITLE
Add French Translation

### PR DESCRIPTION
**Pull request by LoubiTek**
I came across this game by looking for a way to contribute becaus love this.
Having seen that there was not yet a translation in French.
I allowed myself to do so to take care of myself in the late afternoon.

I think have finished for tonight I hope or at the latest in the night... ;)

### CODE REVIEW

**Comment by melvinzhang** [comment]
@LoubiTek Thanks for your contribution! Post an update here when you feel it is ready to merge.

**Comment by lodici** [comment]
Thanks @LoubiTek :+1:. It is entirely up to you but it is also possible to translate the content of the keywords screen as well. [Full instructions are now available in the wiki.](https://github.com/magarena/magarena/wiki/Translating-Magarena#keywords-translation)

**Comment by LoubiTek** [comment]
No problem! I had spotted it and I have already set it aside in the tab of my browser to translate it after finishing this file. :)

**Comment by LoubiTek** [comment]
I have re-read many times now and I think I soon to come to the end!
I created this little txt file to help me understand some things that put me off. :neutral_face:
In addition, I have listed / added / replaced a few words / phrases see letters.
In order to fix if needed later! :sunglasses:

[Help Translate and-for Fix Proposals.txt](https://github.com/magarena/magarena/files/1042658/Help.Translate.and-for.Fix.Proposals.txt)

**Comment by lodici** [comment]
> Line n°41 | 0007471748 = Plane
I guess that means plan? No relationship with a plane in the air?

>Line n°42 | 3092217981 = Scheme
Schème in French.. Or other thing?

These are card types as defined in https://github.com/magarena/magarena/blob/master/src/magic/model/MagicType.java. But these are never actually displayed anywhere as far as I can tell.

>Line n°61 | 3582684418 = Proceed with \"may\" action?
I do not understand! Are we talking about May?

Refers to any action in which you _may_ do something, such as  "You may discard a Plains card...." or "...you may exile target artifact or enchantment.".

> Line n°151 | 3365541470 = Run Firemind Worker
Is the word Firemind translatable?

Refers to the [Project Firemind](http://firemind.ch/) website. So no it should not be translated.

> Line n°158 | 1554441093 = Card Pool:
And Line n°349 | 0451146151 = Card Pool
How to define this? Pool? Is it a group? A packet of cards?

It is used in the deck editor to refer to the list of cards you can choose from to add to your deck. With no filter applied this will be about 11000+ cards.

> Line n°353 | 3493034188 = Deal a new sample hand.
The word Deal in many senses.
Which one and good to use?
Barter, exchange, trade, giving..

As in to "deal the 7 cards that constitute a Hand".

> Line n°365 | 2170721780 = Planeswalkers
Surveyors? If plane does not with the plane in the air. This is not Aviator?
Can left as such as Firemind?

This a type of MTG card, eg.
screenshot00617

> Line n°408 | 1455924259 = Vancouver Mulligan
Not translatable?

Probably not. If you are not sure I would just leave it as-is.

> Line n°183 | 3013682402 = New turn message
And Line n°190 |3639746421 = If the 'New turn message' option is switched on then this setting determines how long (in seconds) it should be displayed. Left-click or space key cancels the delay.
Incomprehension because turn = Tour in French.

Refers to how the long the following UI feature is displayed at the beginning of each turn...
screenshot00618

> Line n°187 | 0293938793 = Elastic play-from arrow
What does this phrase mean?

Yeah, I can see that being difficult to translate. It refers to the following arrow -
screenshot00619

and is displayed in the Preferences -> Gameplay -> Animations settings. The description for the setting should hopefully explain what it does.

**Comment by lodici** [comment]
Thanks for the suggestions and corrections, I have raised issue #1139 to better track these.

**Comment by LoubiTek** [comment]
Heck! I wanted to create a new pull request to add the txt file for the glossary of keywords.
Well it does not matter at least everything will be centralized here for the translation.
I hope it doesn't bother too much, otherwise move it.. @lodici

**Comment by lodici** [comment]
Thanks @LoubiTek. @melvinzhang, should this be merged into the main repo as a single commit or is it better to leave all 10 commits? If you want to merge please go ahead.

**Comment by melvinzhang** [comment]
A single commit would be better.

**Comment by lodici** [comment]
> Will there be in the future an option to do it directly in the game?
> And/or modify in the CFG.

Good point. I have raised #1140 to address this.

**Comment by lodici** [comment]
> A single commit would be better.

Ok thanks, I will have a go at merging everything via a single commit.

**Comment by lodici** [comment]
Committed 97afe5ca2bf93740f1c9fa5709bebf9ea4a5b39a.

**Comment by melvinzhang** [comment]
Thanks @lodici A small suggestion for future PRs, it would be nice to retain the original author of the commit, for git CLI you can specify the author using the `--author` option

**Comment by lodici** [comment]
Thanks, I will try to remember next time. Normally I do a ``git merge --ff-only <pull request branch>`` which automatically commits and retains the original author. This time I did a ``git merge --ff-only --squash <branch>`` but then I had to commit the changes.

**Pull request closed without merging**
