### PR TITLE
Improve Firemind worker

### PR DESCRIPTION
**Pull request by firemind**
Updates are mostly to ensure the features described here can be implemented: http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=16805

No longer shut down after fixed number of duels
Handle temp files for card script submission in a more resource efficient way
Allow seed and AIs to be set dynamically

### CODE REVIEW

**Comment by melvinzhang** [comment]
what's the purpose of the new folder, SCRIPT_ORIGS("origs")?

**Comment by melvinzhang** [comment]
I've gone ahead and merge and changed SCRIPT_ORIGS to SCRIPTS_ORIG

**Comment by firemind** [comment]
The purpose is to have a dedicated directory to store the renamed script files in. If I store them in the main scripts dir java is horribly inefficient in finding the *_orig files there.

**Comment by melvinzhang** [comment]
What's the context for this? When are renamed script files created and how are the used? Are these from script submissions?

**Comment by firemind** [comment]
Yes.

When I implemented the card script submission check I extended the queue worker to allow it to receive updated script files. If one is contained in the duel specification it will move the old script (if there is one) to the origs folder and write the new scripts in the scripts folder.
At the end of each duel it will move all the orig files back to where they were previously.

**Comment by melvinzhang** [comment]
Got it, thanks for taking the time to explain this. The card script submission check is awesome stuff!

**Pull request merged**
