### PR TITLE
Homing Sliver (in progress)

### PR DESCRIPTION
**Pull request by allentiak**
Hi, @melvinzhang!

Could you please check my code?
I don't know what to change to make it work :-)

Thanks in advance!

### CODE REVIEW

**Comment by melvinzhang** [comment]
@allentiak If you see https://github.com/magarena/magarena/blob/f47b0268990a424d02f2bbdad1199403b8267648/release/Magarena/scripts_missing/Homing_Sliver.txt it says status is "not supported: card-modification". This means the game engine does not support adding abilities to cards, only adding abilities to permanents is supported currently.

To implement adding abilities to cards, the Java code of the game engine needs to be extended. You can look at MagicGame.update to see how modification of permanents via static effect is implemented.

**Comment by melvinzhang** [comment]
For something more manageable to start with, look for one of the cards with "needs groovy". Eg https://github.com/magarena/magarena/search?utf8=%E2%9C%93&q=%22needs+groovy%22&type=

These cards can be implemented with just groovy code, without any game engine modifications.

**Comment by allentiak** [comment]
OK. I'll see to than and let you know. Thanks for the reply!

**Comment by melvinzhang** [comment]
There are some nice guides on the wiki. In particular, do checkout https://github.com/magarena/magarena/wiki/Groovy-Basics and the tip on the bottom of the page.

**Comment by allentiak** [comment]
Thanks a lot, Melvin! I'll see that and let you know.

**Pull request closed without merging**
