### PR TITLE
Groovy code for Aether Revolt cards

### PR DESCRIPTION
**Pull request by Fulmene**
Cards added:
- Ajani Unyielding
- Ajani, Valiant Protector
- Exquisite Archangel
- Fatal Push
- Gonti's Machinations
- Kari Zev's Expertise
- Maulfist Revolutionary
- Pia's Revolution
- Rishkar's Expertise
- Scrap Trawler
- Skyship Plunderer
- Sram's Expertise
- Tezzeret, Master of Metal
- Tezzeret's Simulacrum
- Yahenni's Expertise

### CODE REVIEW

**Comment by melvinzhang** [comment]
Looks good! There were a could of groovy code and cards that could not be loaded, working on the fixes now. Did you manage to test these cards in game?

**Comment by melvinzhang** [comment]
Fixes pushed. I've also added the loading check to the CI so we should be able to get advance warnings of these issues.

**Comment by melvinzhang** [comment]
A small stylistic comment, please put the `else` keyword on the same line as the closing curly brace of the `if` block. Eg.
```
if (condition) {
   ...
} else {
   ...
}
```

**Comment by Fulmene** [comment]
I'm really sorry. It seems I got very tired and made so much error. I'm going to fix this myself.

**Comment by ShawnieBoy** [comment]
Don't worry, it's easily done - Always happy for new contributors. The only problem at the moment is with "target permanent or player" not currently implemented as a target choice for Maulfist Revolutionary

**Comment by Fulmene** [comment]
Pushed that fix to my fork. I'm seeing if there are other problems before filing another pull request.

**Comment by melvinzhang** [comment]
Happy to help fix bugs, easier than creating a card from scratch. Our CI tests is done randomly on a subset of cards, so sometimes issues crop up later. You can see the stack trace for Maulfist Revolutionary at https://circleci.com/gh/magarena/magarena/3124

**Pull request merged**
