### PR TITLE
Update Português.txt

### PR DESCRIPTION
**Pull request by PalladiaMors**
Correcting mistake and testing updating the translation through GitHub.

### CODE REVIEW

**Comment by lodici** [comment]
@melvinzhang for such a simple change as this I can do the merge but I suspect just clicking on the Merge pull request button does not do the rebase method which you advocate. Please can you confirm the best method to use. Thanks.

**Comment by lodici** [comment]
Reckon I understand how it works now, at least for updates to a translation file. @PalladiaMors any future changes you make should not take so long to appear in the main repo, so if you are happy with the process can I suggest you maintain the github file and replace the attachment in the forum with a link to the raw view of the file - [``https://raw.githubusercontent.com/magarena/magarena/master/release/Magarena/translations/Portugu%C3%AAs.txt``](https://raw.githubusercontent.com/magarena/magarena/master/release/Magarena/translations/Portugu%C3%AAs.txt)

**Comment by melvinzhang** [comment]
@lodici Your right, github does not do a rebase, I feel that in the git history pull requests commits should look no different from regular commits. The merge looks good. ks good, you manually ran rebase?

**Comment by lodici** [comment]
I used a slight variation on GitHub's recommended approach -

```
    $ git checkout -b PalladiaMors-patch-100 master
    $ git pull https://github.com/PalladiaMors/magarena.git patch-100
    $ git checkout master
    $ git merge --ff-only PalladiaMors-patch-100
    $ git push origin master
```

Instead of ``no-ff`` I used ``--ff-only`` which will fast-forward if it can or fail otherwise. I think that this is simpler than rebase, especially for this specific case of merging changes made to a translation file and because it does not alter the commit-hashes (unlike rebase) it seems to integrate cleaner into the main repo, correctly flags as merged (purple Merged tag) and closes the pull request. If ``--ff-only`` failed then I would revert to the rebase method.

**Comment by melvinzhang** [comment]
I see, yeah if the commit is made on top of the current last commit merge --ff-ony works. In this case, for rebase, the commit hash will also remain the same as the parent commit did not get changed.

**Pull request merged**
